// examples/vue-multistep/src/components/StepReview.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useLiveSchema } from '@liveschema/vue'
import { form as orderForm } from '@/schemas'

const props = defineProps<{ data: Record<string, unknown> }>()

const { activeFields } = useLiveSchema(orderForm, () => props.data)
const activeFieldKeys = computed(() => Object.keys(activeFields.value))

function display(value: unknown): string {
  if (value === undefined || value === null) return '—'
  if (Array.isArray(value)) return value.join(', ')
  if (typeof value === 'object') {
    return Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${k}: ${display(v)}`)
      .join(' · ')
  }
  return String(value)
}

function humanize(field: string): string {
  return field.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase())
}
</script>

<template>
  <h2>Review</h2>
  <dl class="review">
    <template v-for="key in activeFieldKeys" :key="key">
      <dt>{{ humanize(key) }}</dt>
      <dd>{{ display(props.data[key]) }}</dd>
    </template>
  </dl>
</template>

<style scoped>
.review {
  display: grid;
  grid-template-columns: max-content 1fr;
  gap: 0.4rem 1rem;
}
.review dt {
  color: #888;
  font-size: 0.85rem;
}
.review dd {
  margin: 0;
}
</style>

// packages/examples/react-example/src/StepReview.tsx
import { activeFields } from 'liveschema'
import { form } from './schemas'
import { humanize } from './stepLabels'

function display(value: unknown): string {
  if (value === undefined || value === null) return '—'
  if (Array.isArray(value)) return value.join(', ')
  if (typeof value === 'object') {
    return Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${k}: ${display(v)}`)
      .join(' · ')
  }
  return String(value)
}

export function StepReview({ data }: { data: Record<string, unknown> }) {
  const items = activeFields(form, data).map((step) => ({
    key: step.key,
    value: step.value,
  }))
  return (
    <>
      <h2>Review</h2>
      <dl className="review">
        {items.map((item) => (
          <div key={item.key} className="review-row">
            <dt>{humanize(item.key)}</dt>
            <dd>{display(item.value)}</dd>
          </div>
        ))}
      </dl>
    </>
  )
}
