// examples/vue-multistep/src/components/steps/CheckboxStep.vue
<script setup lang="ts">
import { useField } from 'vee-validate'
const props = defineProps<{
  path: string
  question: string
  confirmLabel?: string
}>()
const { value, errorMessage } = useField<boolean | undefined>(() => props.path)
</script>

<template>
  <h2>{{ question }}</h2>
  <label class="confirm">
    <input
      type="checkbox"
      :checked="value === true"
      @change="value = ($event.target as HTMLInputElement).checked"
    />
    <span>{{ props.confirmLabel ?? 'Yes' }}</span>
  </label>
  <p v-if="errorMessage" class="error">{{ errorMessage }}</p>
</template>

<style scoped>
.confirm {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  margin-top: 0.5rem;
  cursor: pointer;
}
</style>

// examples/react-example/src/steps/CheckboxStep.tsx
import type { AdoptionForm } from '../formTypes'

type Props = {
  form: AdoptionForm
  path: string
  question: string
  confirmLabel?: string
}

export function CheckboxStep({ form, path, question, confirmLabel = 'Yes' }: Props) {
  return (
    <div>
      <h2>{question}</h2>
      <form.Field name={path}>
        {(field: {
          state: { value: boolean | undefined; meta: { errors: unknown[] } }
          handleChange: (v: boolean) => void
        }) => (
          <>
            <label className="confirm">
              <input
                type="checkbox"
                checked={field.state.value === true}
                onChange={(e) => field.handleChange(e.target.checked)}
              />
              <span>{confirmLabel}</span>
            </label>
            {field.state.meta.errors.length > 0 && (
              <p className="error">{String(field.state.meta.errors[0])}</p>
            )}
          </>
        )}
      </form.Field>
    </div>
  )
}
